export const ProfileVerification = {
  FIRSTNAME_VERIFIED: 'First name verified successfully.',
  FIRSTNAME_UNVERIFED: 'First name is missing.',
  LASTNAME_VERIFIED: 'Last name verified successfully.',
  LASTNAME_UNVERIFED: 'Last name is missing.',
  EMAIL_VERIFIED: 'You have confirmed your email. A confirmed email is important to allow us to securely communicate with you.',
  EMAIL_UNVERIFIED: 'Your email has not yet been verified.',
  PHONENUMBER_VERIFIED: 'Your number is only shared with other LockTrip members once you have confirmed a booking.',
  PHONENUMBER_UNVERIFIED: 'Phone number is missing.',
  COUNTRY_VERIFIED: 'Country verified successfully.',
  COUNTRY_UNVERIFIED: 'Country is missing.',
  CITY_VERIFIED: 'City verified successfully.',
  CITY_UNVERIFIED: 'City is missing.',
  ADDRESS_VERIFIED: 'Address verified successfully.',
  ADDRESS_UNVERIFIED: 'Address is missing.',
  ZIPCODE_VERIFIED: 'Zip code verified successfully.',
  ZIPCODE_UNVERIFIED: 'Zip code is missing.',
};
