export const ProfileVerification = {
  EMAILADDRESS_VERIFIED: 'You have confirmed your email. A confirmed email is important to allow us to securely communicate with you',
  EMAILADDRESS_UNVERIFIED: 'Email is missing',
  PHONENUMBER_VERIFIED: 'Your number is only shared with another Airbnb member once you have confirmed booking',
  PHONENUMBER_UNVERIFIED: 'Phone number is missing',
  BIRTHDAY_VERIFIED: 'Birthday existing',
  BIRTHDAY_UNVERIFIED: 'Birthday is missing',
  ADDRESS_VERIFIED: 'Address existing',
  ADDRESS_UNVERIFIED: 'Address is missing',
  NATIONALITY_VERIFIED: 'Nationality existing',
  NATIONALITY_UNVERIFIED: 'Nationality is missing',
  CITY_VERIFIED: 'City is existing',
  CITY_UNVERIFIED: 'City is missing',
  COUNTRY_VERIFIED: 'Country is existing',
  COUNTRY_UNVERIFIED: 'Country is missing',
  GENDER_VERIFIED: 'Gender is existing',
  GENDER_UNVERIFIED: 'Gender is missing',
  LASTNAME_VERIFIED: 'dasdsa',
  LASTNAME_UNVERIFED: 'dasdsad'
};
